### PR TITLE
Add Context API

### PR DESCRIPTION
**Pull request by den1k**
Inspired by @martinklepsch's #30 

- adds a context API under `sieppari.core/execute-context`.
- updated `sieppari.core/execute` to use execute context.
- updated tests
- added tests for execute-context
 - updated readme

Since this is performance critical I reran the performance benchmarks, once before and once after my changes which shows that performance is overall the same. See updated benchmarks below.

### CODE REVIEW

**Comment by den1k** [comment]
@miikka @ikitommi please let me know if anything besides the conflicting README is blocking this PR.

**Comment by den1k** [comment]
Merged perf regression fixes and reran benchmarks:

https://gist.github.com/den1k/ff82ca3ba7d8dc551de3f4a5fa642849

**Comment by miikka** [comment]
Tommi will do some perf checks and get back to you.

**Comment by ikitommi** [comment]
Hi, I'll check the code in detail and run the benchmarks on my local machine, hopefully in the following next few days. Cheers.

**Comment by ikitommi** [comment]
Hi. Run the benchmarks on my local machine. `s/execute` is ~100% slower when using  `s/execute-context` internally. But it's easy to split the code back to use 2 tracks. Will merge this and fix the perf on top of this. Big thanks for the PR!

**Comment by ikitommi** [comment]
https://github.com/metosin/sieppari/pull/38

**Pull request merged**
