### PR TITLE
Fix protocol extension (for cljs)

### PR DESCRIPTION
**Pull request by zelark**
Relates to #34

https://stackoverflow.com/questions/16894465/extend-protocol-in-clojurescript-to-get-value-from-native-js-object

### CODE REVIEW

**Comment by ikitommi** [comment]
Hi. Actually `default` would cover all cases: https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/core.cljc#L1312-L1328. Could you change to that?

**Comment by zelark** [comment]
Hi, sure.

**Comment by zelark** [comment]
Just changed. Didn't know about `default`. Thank you.

**Comment by ikitommi** [comment]
Thanks!

**Pull request merged**
